### ISSUE TITLE
Output of offending filename?

### ISSUE THREAD

**Issue by DooDip** [oalsaab/video-sorting-ffprobe#2]
This` works great unless I come across a corrupted video. Then I get this error.

```

`Sorting` video files...
Traceback (most recent call last):
  File "/root/video-sorting-ffprobe/sort_class.py", line 45, in dimensions_sort
    width = self.video_json['streams'][0]['width']
KeyError: 'streams'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/video-sorting-ffprobe/main.py", line 60, in <module>
    main()
  File "/root/video-sorting-ffprobe/main.py", line 26, in main
    process.dimensions_sort()
  File "/root/video-sorting-ffprobe/sort_class.py", line 48, in dimensions_sort
    width = self.video_json['streams'][1]['width']
KeyError: `'streams'`
```

Unfortunately it doesn't show the filename which is corrupted. Is there any way to find this out? Thanks!

**Comment by oalsaab** [comment]
I assume the video you were trying to sort was corrupted. The error is difficult to reproduce because I do not have access to the videos you are trying to sort, but I assume the error will always propagate itself in a KeyError if the multimedia stream is corrupted.

I have updated the code to catch these errors and output the offending filenames, hopefully it works for you now.
